services:
  varnish:
    image: varnish:stable
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
      - ./tests:/etc/varnish/tests
    environment:
      VARNISH_HTTP_PORT: 8080
    ports:
      - 8080:80
  web1:
    image: php:8.2-apache
    volumes:
      - ./site:/var/www/html
  web2:
    image: php:8.2-apache
    volumes:
      - ./site:/var/www/html
  docs:
    image: klakegg/hugo:latest
    ports:
      - 1313:1313
    volumes:
      - ./docs:/src
    command: server -D --poll 700ms
